name: Autograding Tests
'on':
- push
- repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Build
      id: build
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: Build
        setup-command: ''
        command: "./gradlew build"
        timeout: 10
        max-score: 5
    - name: Coverage
      id: coverage
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: Coverage
        setup-command: ''
        command: "./gradlew test jacocoTestCoverageVerification"
        timeout: 10
        max-score: 5
    - name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1
      env:
        BUILD_RESULTS: "${{steps.build.outputs.result}}"
        COVERAGE_RESULTS: "${{steps.coverage.outputs.result}}"
      with:
        runners: build,coverage
